# DEPLOY STOCK WIDGET WAR APPLICATIONS TO JBOSS DEPLOYMENT DIRECTORY

# DEPLOY STOCK WIDGETS BACK END REST API's
cp ./war/swAPI-0.0.1-SNAPSHOT.war $wfDeployDir

# DEPLOY STOCK WIDGETS FRONT END WEB APPLICATION
cp ./war/swWeb-0.0.1-SNAPSHOT.war $wfDeployDir
