# DEPLOY STOCK WIDGET WAR APPLICATIONS TO JBOSS DEPLOYMENT DIRECTORY

wfDeployDir=$1

# DEPLOY STOCK WIDGETS BACK END REST API's
echo "EXECUTING cp ./war/swAPI-0.0.1-SNAPSHOT.war $wfDeployDir"
cp ./war/swAPI-0.0.1-SNAPSHOT.war $wfDeployDir

# DEPLOY STOCK WIDGETS FRONT END WEB APPLICATION
echo "EXECUTING cp ./war/swWeb-0.0.1-SNAPSHOT.war $wfDeployDir"
cp ./war/swWeb-0.0.1-SNAPSHOT.war $wfDeployDir
